### ISSUE TITLE
Segfault when compiling with clang

### ISSUE THREAD

**Issue by ransel117** [Ransel117/ranmath#1]
For some reason when compiling with clang without optimizations rm_vec4_wrapf segfaults on my machine. It may happen with other functions aswell, will look into it.
Compiling with any of ```-O1```, ```-O2``` or ```-O3``` fixes the segfault...

**Comment by Ransel117** [comment]
Tested almost all of the vec4 functions and for some reason almost all of them segfaults?!
maybe it's an issue of how clang handles intrinsics?

**Comment by Ransel117** [comment]
Update: it seems to be the same on windows using cl...

**Comment by Ransel117** [comment]
Update: it works on x64 Native tools etc. using cl, but not on x86 using cl. Might just be my pc though.

**Comment by Ransel117** [comment]
Seems to be fixed right now. Probably because of better way of converting from struct to float* using unions instead of doing some wacky pointer stuff.
